{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "267e3026-fe46-4301-a1d9-8a13b86f542d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "📦 Required packages:\n",
      "    Essential: googlemaps, pandas\n",
      "    For Excel: openpyxl\n",
      "💻 Install/Upgrade with: pip install --upgrade googlemaps pandas openpyxl\n",
      "======================================================================\n",
      "🔑 Enhanced Google Maps API Business Locator - CSV & Excel Output\n",
      "======================================================================\n",
      "✅ Excel support: Available (openpyxl found)\n",
      "\n",
      "--- API Key Setup Guide ---\n",
      "To use this tool, you need a Google Maps API Key with specific APIs enabled.\n",
      "If you encounter 'REQUEST_DENIED' errors, please follow these steps carefully:\n",
      "===================================================================\n",
      "1. 🌐  Go to Google Cloud Console: https://console.cloud.google.com\n",
      "2. 📁  Select or Create a Project. (Top left dropdown menu)\n",
      "3. 💳  Enable Billing for your project. (Required for all Places API usage)\n",
      "4. 🔧  Enable Necessary APIs:\n",
      "      Navigate to 'APIs & Services' > 'Enabled APIs & Services'.\n",
      "      Click '+ ENABLE APIS AND SERVICES' and search for & enable:\n",
      "      •  'Places API' (This is crucial for the script to work)\n",
      "5. 🔑  Create or Get Your API Key:\n",
      "      Go to 'APIs & Services' > 'Credentials'.\n",
      "      Create a new API key or copy an existing one.\n",
      "6. 🔒  Restrict Your API Key (Highly Recommended for security):\n",
      "      Edit your API key and under 'API restrictions', select 'Restrict key' to 'Places API'.\n",
      "===================================================================\n",
      "Once these steps are done, enter your API key below.\n"
     ]
    }
   ],
   "source": [
    "import googlemaps\n",
    "import pandas as pd\n",
    "import time\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "class BusinessLocator:\n",
    "    def __init__(self, api_key):\n",
    "        \"\"\"\n",
    "        Initialize the BusinessLocator with Google Maps API key\n",
    "        \"\"\"\n",
    "        # Initialize Google Maps client. The 'googlemaps' library automatically\n",
    "        # handles the underlying API version when calling methods like find_place\n",
    "        # and place, especially when specific field names (camelCase for new API)\n",
    "        # or input_type are provided.\n",
    "        self.gmaps = googlemaps.Client(key=api_key)\n",
    "        \n",
    "        # Enhanced business types - added Jio and Vi service centers\n",
    "        self.business_types = {\n",
    "            'Airtel Service Centers': ['Airtel store', 'Airtel service center', 'Airtel outlet', 'Airtel recharge center'],\n",
    "            'Jio Service Centers': ['Jio store', 'Jio service center', 'Jio outlet', 'Jio digital store', 'Reliance Jio store'],\n",
    "            'Vi Service Centers': ['Vi store', 'Vi service center', 'Vodafone Idea store', 'VI outlet', 'Vodafone store', 'Idea store'],\n",
    "            'Gold Showrooms': ['gold jewellery shop', 'gold showroom', 'jewellery store', 'gold jewelry', 'precious metals'],\n",
    "            'Car Showrooms': ['car showroom', 'car dealer', 'automobile showroom', 'auto dealer', 'vehicle showroom'],\n",
    "            'Shopping Malls': ['shopping mall', 'shopping center', 'mall', 'shopping complex', 'retail plaza'],\n",
    "            'Luxury Fashion Stores': ['luxury boutique', 'designer store', 'high-end fashion', 'premium fashion', 'designer clothing'],\n",
    "            'Department Stores': ['department store', 'luxury department store', 'premium retail store', 'multi-brand store'],\n",
    "            'Luxury Brand Stores': ['luxury store', 'premium brand', 'designer brand store', 'high-end retail', 'luxury boutique'],\n",
    "            'Banks & ATMs': ['bank', 'ATM', 'banking center', 'financial services', 'private bank'],\n",
    "            'Insurance Companies': ['insurance office', 'insurance company', 'life insurance', 'general insurance', 'insurance agency'],\n",
    "            'Real Estate Offices': ['real estate office', 'property dealer', 'real estate agent', 'property consultant', 'real estate firm'],\n",
    "            'Premium Hotels': ['luxury hotel', '5 star hotel', '4 star hotel', 'premium hotel', 'business hotel'],\n",
    "            'Restaurants & Fine Dining': ['fine dining restaurant', 'premium restaurant', 'multi-cuisine restaurant', 'luxury restaurant'],\n",
    "            'Beauty & Wellness Centers': ['beauty salon', 'spa', 'wellness center', 'beauty parlor', 'premium salon']\n",
    "        }\n",
    "    \n",
    "    def get_detailed_place_info(self, place_id):\n",
    "        \"\"\"\n",
    "        Get detailed information for a specific place including phone and website.\n",
    "        Uses Places API (New) field mask for efficiency and future compatibility.\n",
    "        \"\"\"\n",
    "        try:\n",
    "            # Use Places API (New) field names (camelCase) for requesting specific details.\n",
    "            # The 'fields' parameter in googlemaps.Client.place() is implicitly used as a fieldMask\n",
    "            # for the newer Places API if the underlying API is enabled for the project.\n",
    "            place_details = self.gmaps.place(\n",
    "                place_id=place_id,\n",
    "                fields=[\n",
    "                    'name', 'formattedAddress', 'formattedPhoneNumber', 'website',\n",
    "                    'rating', 'userRatingsTotal', 'priceLevel', 'businessStatus',\n",
    "                    'openingHours.weekdayDescriptions', 'types', 'geometry.location' # Ensure geometry.location is requested for lat/lng\n",
    "                ]\n",
    "            )\n",
    "            \n",
    "            # The 'place' method returns a dictionary with 'result' and 'html_attributions'\n",
    "            # Check for 'result' in the response directly\n",
    "            if 'result' in place_details:\n",
    "                return place_details['result']\n",
    "            else:\n",
    "                # Handle cases where 'result' might be missing but status is OK, or status is not OK\n",
    "                print(f\"    ⚠️ No detailed result found for place {place_id} (Status: {place_details.get('status', 'N/A')})\")\n",
    "                return None\n",
    "                \n",
    "        except Exception as e:\n",
    "            print(f\"    ⚠️ Error getting details for place {place_id}: {str(e)[:100]}...\")\n",
    "            return None\n",
    "    \n",
    "    def search_places(self, city, business_type, search_terms):\n",
    "        \"\"\"\n",
    "        Enhanced search that fetches detailed place information including phone and website.\n",
    "        Uses Places API (New) 'find_place_from_text' for initial search.\n",
    "        \"\"\"\n",
    "        places_data = []\n",
    "        seen_places = set()  # Track duplicates by place_id\n",
    "        \n",
    "        for term in search_terms:\n",
    "            try:\n",
    "                # Use find_place_from_text (part of Places API New) for initial search.\n",
    "                # 'input_type' is required for find_place.\n",
    "                # 'fields' here are for the initial find_place response, often basic info like place_id.\n",
    "                # Request 'place_id' and 'name' for candidate identification, and 'geometry.location'\n",
    "                # for initial lat/lng if available without a detailed call.\n",
    "                places_result = self.gmaps.find_place(\n",
    "                    input=f\"{term} in {city}\",\n",
    "                    input_type='textquery',\n",
    "                    fields=['place_id', 'displayName', 'location'] # 'displayName' for name, 'location' for lat/lng in new API\n",
    "                )\n",
    "                \n",
    "                # The find_place method returns 'candidates' not 'results' for the places found.\n",
    "                if 'candidates' not in places_result or not places_result['candidates']:\n",
    "                    print(f\"    No candidates found for '{term} in {city}'.\")\n",
    "                    continue\n",
    "\n",
    "                for place in places_result['candidates']:\n",
    "                    place_id = place.get('place_id')\n",
    "                    \n",
    "                    if not place_id or place_id in seen_places:\n",
    "                        continue\n",
    "                    \n",
    "                    seen_places.add(place_id)\n",
    "                    \n",
    "                    # Use 'displayName' for the name from the find_place response\n",
    "                    place_name = place.get('displayName', {}).get('text', 'Unknown')\n",
    "                    print(f\"    🔍 Getting details for: {place_name}\")\n",
    "                    \n",
    "                    # Get detailed information using the new method which uses field mask\n",
    "                    detailed_info = self.get_detailed_place_info(place_id)\n",
    "                    \n",
    "                    if detailed_info:\n",
    "                        # Extract phone number and website - using correct field names (camelCase from new API)\n",
    "                        phone = detailed_info.get('formattedPhoneNumber', '').strip()\n",
    "                        website = detailed_info.get('website', '').strip()\n",
    "                        opening_hours = self._format_opening_hours(detailed_info.get('openingHours')) # 'openingHours' is camelCase\n",
    "                        \n",
    "                        # Only include places with meaningful data (skip if all key fields are empty)\n",
    "                        # We use 'formattedAddress' for a more robust check in the new API context.\n",
    "                        if not phone and not website and not detailed_info.get('rating') and not detailed_info.get('formattedAddress'):\n",
    "                            continue\n",
    "                        \n",
    "                        # Extract location, handling potential absence gracefully\n",
    "                        latitude = detailed_info.get('geometry', {}).get('location', {}).get('latitude')\n",
    "                        longitude = detailed_info.get('geometry', {}).get('location', {}).get('longitude')\n",
    "\n",
    "                        # Skip if essential location data is missing\n",
    "                        if latitude is None or longitude is None:\n",
    "                            print(f\"    Skipping {place_name}: Missing latitude/longitude.\")\n",
    "                            continue\n",
    "\n",
    "                        place_details = {\n",
    "                            'Business_Type': business_type,\n",
    "                            'Name': detailed_info.get('name', '').strip(), # Original name field is still 'name' in detailed response\n",
    "                            'Address': detailed_info.get('formattedAddress', '').strip(), # camelCase\n",
    "                            'Phone': phone if phone else '',\n",
    "                            'Website': website if website else '',\n",
    "                            'Latitude': latitude,\n",
    "                            'Longitude': longitude,\n",
    "                            'Rating': detailed_info.get('rating', ''),\n",
    "                            'Total_Ratings': detailed_info.get('userRatingsTotal', ''), # camelCase\n",
    "                            'Price_Level': self._get_price_level(detailed_info.get('priceLevel')), # camelCase\n",
    "                            'Business_Status': detailed_info.get('businessStatus', ''), # camelCase\n",
    "                            'Types': ', '.join(detailed_info.get('types', [])), # camelCase\n",
    "                            'Place_ID': place_id,\n",
    "                            'City': city,\n",
    "                            'Search_Term': term\n",
    "                        }\n",
    "                        \n",
    "                        places_data.append(place_details)\n",
    "                        print(f\"    ✅ Added: {detailed_info.get('name', 'Unknown')}\")\n",
    "                    \n",
    "                    # Add delay between detailed API calls to avoid rate limiting\n",
    "                    time.sleep(0.5)\n",
    "                \n",
    "                # Enhanced delay between search terms\n",
    "                time.sleep(1.0)\n",
    "                \n",
    "            except googlemaps.exceptions.ApiError as e:\n",
    "                print(f\"  ❌ API Error searching for {term}: {e}\")\n",
    "                continue\n",
    "            except Exception as e:\n",
    "                print(f\"  ⚠️  Error searching for {term}: {str(e)[:100]}...\")\n",
    "                continue\n",
    "        \n",
    "        return places_data\n",
    "    \n",
    "    def _format_opening_hours(self, opening_hours):\n",
    "        \"\"\"\n",
    "        Format opening hours information.\n",
    "        Expects 'openingHours' structure from Places API (New), which contains 'weekdayDescriptions'.\n",
    "        \"\"\"\n",
    "        if not opening_hours:\n",
    "            return ''\n",
    "        \n",
    "        # In Places API (New), human-readable opening hours are typically in 'weekdayDescriptions'\n",
    "        if 'weekdayDescriptions' in opening_hours:\n",
    "            return '; '.join(opening_hours['weekdayDescriptions'])\n",
    "        \n",
    "        return ''\n",
    "    \n",
    "    def _get_price_level(self, price_level):\n",
    "        \"\"\"Convert numeric price level to descriptive text\"\"\"\n",
    "        if price_level is None:\n",
    "            return ''\n",
    "        \n",
    "        price_map = {\n",
    "            0: 'Free',\n",
    "            1: 'Inexpensive',\n",
    "            2: 'Moderate',\n",
    "            3: 'Expensive',\n",
    "            4: 'Very Expensive'\n",
    "        }\n",
    "        return price_map.get(price_level, '')\n",
    "    \n",
    "    def get_all_businesses(self, city):\n",
    "        \"\"\"\n",
    "        Get all business types for a given city with enhanced progress tracking\n",
    "        \"\"\"\n",
    "        all_data = []\n",
    "        \n",
    "        print(f\"\\n🔍 Searching for businesses in {city}...\")\n",
    "        print(f\"📊 Total categories to search: {len(self.business_types)}\")\n",
    "        \n",
    "        for idx, (business_type, search_terms) in enumerate(self.business_types.items(), 1):\n",
    "            print(f\"  📍 [{idx}/{len(self.business_types)}] Searching for {business_type}...\")\n",
    "            \n",
    "            business_data = self.search_places(city, business_type, search_terms)\n",
    "            all_data.extend(business_data)\n",
    "            \n",
    "            print(f\"      ✅ Found {len(business_data)} {business_type.lower()}\")\n",
    "            \n",
    "            # Add small delay between categories\n",
    "            if idx < len(self.business_types):\n",
    "                time.sleep(1.0)\n",
    "        \n",
    "        print(f\"\\n🎯 Total businesses found: {len(all_data)}\")\n",
    "        return all_data\n",
    "    \n",
    "    def clean_data(self, data):\n",
    "        \"\"\"\n",
    "        Clean data by removing rows with too many empty values.\n",
    "        Adjusted to use 'Address' instead of 'Opening_Hours' for key field check,\n",
    "        as Opening_Hours might not always be present or critical for basic entry.\n",
    "        \"\"\"\n",
    "        if not data:\n",
    "            return data\n",
    "        \n",
    "        cleaned_data = []\n",
    "        for item in data:\n",
    "            # Count non-empty values (excluding location data which should always be present)\n",
    "            non_empty_count = 0\n",
    "            \n",
    "            # Check key fields. 'Address' is usually a reliable indicator of useful data.\n",
    "            key_fields = ['Name', 'Address', 'Phone', 'Website', 'Rating'] # Removed 'Opening_Hours' as it's less critical for basic filtering\n",
    "            \n",
    "            for field in key_fields:\n",
    "                if item.get(field) and str(item[field]).strip() and item[field] != '':\n",
    "                    non_empty_count += 1\n",
    "            \n",
    "            # Keep record if at least 2 out of 5 key fields have data (adjusted threshold)\n",
    "            if non_empty_count >= 2:\n",
    "                cleaned_data.append(item)\n",
    "        \n",
    "        print(f\"🧹 Data cleaning: {len(data)} → {len(cleaned_data)} records (removed {len(data) - len(cleaned_data)} low-quality entries)\")\n",
    "        return cleaned_data\n",
    "    \n",
    "    def save_to_files(self, data, city):\n",
    "        \"\"\"\n",
    "        Enhanced save function with both CSV and Excel output\n",
    "        \"\"\"\n",
    "        if not data:\n",
    "            print(\"❌ No data to save!\")\n",
    "            return\n",
    "        \n",
    "        # Clean the data first\n",
    "        cleaned_data = self.clean_data(data)\n",
    "        \n",
    "        if not cleaned_data:\n",
    "            print(\"❌ No valid data remaining after cleaning!\")\n",
    "            return\n",
    "        \n",
    "        # Create DataFrame\n",
    "        df = pd.DataFrame(cleaned_data)\n",
    "        \n",
    "        # Remove duplicate entries\n",
    "        df = df.drop_duplicates(subset=['Name', 'Address'], keep='first')\n",
    "        \n",
    "        # Replace empty values with empty strings for better display\n",
    "        df = df.fillna('')\n",
    "        \n",
    "        # Sort by business type and rating (handle empty ratings)\n",
    "        df['Rating_Sort'] = pd.to_numeric(df['Rating'], errors='coerce').fillna(0)\n",
    "        df = df.sort_values(['Business_Type', 'Rating_Sort'], ascending=[True, False])\n",
    "        df = df.drop(columns=['Rating_Sort'])  # Remove helper column\n",
    "        \n",
    "        # Create filename with timestamp\n",
    "        timestamp = datetime.now().strftime(\"%Y%m%d_%H%M%S\")\n",
    "        base_filename = f\"{city.replace(' ', '_')}_businesses_{timestamp}\"\n",
    "        \n",
    "        # Create summary data\n",
    "        summary_data = []\n",
    "        for business_type in self.business_types.keys():\n",
    "            business_df = df[df['Business_Type'] == business_type]\n",
    "            if not business_df.empty:\n",
    "                # Handle rating calculation safely\n",
    "                numeric_ratings = pd.to_numeric(business_df['Rating'], errors='coerce')\n",
    "                avg_rating = numeric_ratings.mean()\n",
    "                \n",
    "                # Count entries with phone numbers and websites\n",
    "                phone_count = len(business_df[business_df['Phone'].astype(str).str.strip() != ''])\n",
    "                website_count = len(business_df[business_df['Website'].astype(str).str.strip() != ''])\n",
    "                \n",
    "                summary_data.append({\n",
    "                    'Business_Type': business_type,\n",
    "                    'Total_Count': len(business_df),\n",
    "                    'With_Phone': phone_count,\n",
    "                    'With_Website': website_count,\n",
    "                    'Phone_Percentage': f\"{round((phone_count/len(business_df))*100, 1)}%\",\n",
    "                    'Website_Percentage': f\"{round((website_count/len(business_df))*100, 1)}%\",\n",
    "                    'Avg_Rating': round(avg_rating, 2) if not pd.isna(avg_rating) else 'No Ratings'\n",
    "                })\n",
    "        \n",
    "        summary_df = pd.DataFrame(summary_data) if summary_data else pd.DataFrame()\n",
    "        \n",
    "        # === CSV OUTPUT ===\n",
    "        print(f\"\\n💾 Saving CSV files...\")\n",
    "        \n",
    "        # Save main CSV file\n",
    "        main_csv_filename = f\"{base_filename}_all_data.csv\"\n",
    "        df.to_csv(main_csv_filename, index=False, encoding='utf-8-sig')\n",
    "        \n",
    "        # Save summary CSV\n",
    "        if not summary_df.empty:\n",
    "            summary_csv_filename = f\"{base_filename}_summary.csv\"\n",
    "            summary_df.to_csv(summary_csv_filename, index=False, encoding='utf-8-sig')\n",
    "        \n",
    "        # Create separate CSV files for each business type\n",
    "        csv_business_files = []\n",
    "        for business_type in self.business_types.keys():\n",
    "            business_df = df[df['Business_Type'] == business_type]\n",
    "            if not business_df.empty:\n",
    "                clean_name = business_type.replace(' ', '_').replace('&', 'and').replace('/', '_')\n",
    "                business_csv_filename = f\"{base_filename}_{clean_name}.csv\"\n",
    "                business_df.to_csv(business_csv_filename, index=False, encoding='utf-8-sig')\n",
    "                csv_business_files.append(business_csv_filename)\n",
    "        \n",
    "        # === EXCEL OUTPUT ===\n",
    "        print(f\"📊 Saving Excel file...\")\n",
    "        \n",
    "        try:\n",
    "            # Save single Excel file with multiple sheets\n",
    "            main_excel_filename = f\"{base_filename}_complete.xlsx\"\n",
    "            \n",
    "            with pd.ExcelWriter(main_excel_filename, engine='openpyxl') as writer:\n",
    "                # Sheet 1: All data combined\n",
    "                df.to_excel(writer, sheet_name='All_Businesses', index=False)\n",
    "                \n",
    "                # Sheet 2: Summary sheet\n",
    "                if not summary_df.empty:\n",
    "                    summary_df.to_excel(writer, sheet_name='Summary', index=False)\n",
    "                \n",
    "                # Individual business type sheets\n",
    "                for business_type in self.business_types.keys():\n",
    "                    business_df = df[df['Business_Type'] == business_type]\n",
    "                    if not business_df.empty:\n",
    "                        # Clean sheet name (Excel has restrictions)\n",
    "                        clean_sheet_name = business_type.replace(' ', '_').replace('&', 'and').replace('/', '_')\n",
    "                        # Truncate if too long (Excel sheet name limit is 31 characters)\n",
    "                        if len(clean_sheet_name) > 31:\n",
    "                            clean_sheet_name = clean_sheet_name[:28] + \"...\"\n",
    "                        \n",
    "                        business_df.to_excel(writer, sheet_name=clean_sheet_name, index=False)\n",
    "            \n",
    "            excel_success = True\n",
    "            excel_business_files = []  # No separate files needed\n",
    "            \n",
    "        except ImportError:\n",
    "            print(\"⚠️  Excel export requires 'openpyxl' package. Install with: pip install openpyxl\")\n",
    "            excel_success = False\n",
    "            main_excel_filename = \"Not created (missing openpyxl)\"\n",
    "        except Exception as e:\n",
    "            print(f\"⚠️  Error creating Excel file: {e}\")\n",
    "            excel_success = False\n",
    "            main_excel_filename = \"Error during creation\"\n",
    "        \n",
    "        # === OUTPUT SUMMARY ===\n",
    "        print(f\"\\n✅ Data saved successfully in both formats!\")\n",
    "        print(\"=\" * 80)\n",
    "        \n",
    "        print(f\"📄 CSV FILES:\")\n",
    "        print(f\"    📊 Main file: {main_csv_filename}\")\n",
    "        if not summary_df.empty:\n",
    "            print(f\"    📈 Summary file: {summary_csv_filename}\")\n",
    "        print(f\"    📁 Individual category files: {len(csv_business_files)} files created\")\n",
    "        \n",
    "        print(f\"\\n📊 EXCEL FILE:\")\n",
    "        if excel_success:\n",
    "            print(f\"    📗 Complete workbook: {main_excel_filename}\")\n",
    "            print(f\"    📑 Contains {len([bt for bt in self.business_types.keys() if len(df[df['Business_Type'] == bt]) > 0]) + 2} sheets:\")\n",
    "            print(f\"        • All_Businesses (combined data)\")\n",
    "            print(f\"        • Summary (statistics)\")\n",
    "            for business_type in self.business_types.keys():\n",
    "                if len(df[df['Business_Type'] == business_type]) > 0:\n",
    "                    clean_name = business_type.replace(' ', '_').replace('&', 'and').replace('/', '_')\n",
    "                    if len(clean_name) > 31:\n",
    "                        clean_name = clean_name[:28] + \"...\"\n",
    "                    print(f\"        • {clean_name}\")\n",
    "        else:\n",
    "            print(f\"    ❌ Excel file: {main_excel_filename}\")\n",
    "            print(f\"    💡 To enable Excel export: pip install openpyxl\")\n",
    "        \n",
    "        print(f\"\\n📈 DATA SUMMARY:\")\n",
    "        print(f\"    🏢 Total unique records: {len(df)}\")\n",
    "        print(f\"    📋 Business categories: {len([bt for bt in self.business_types.keys() if len(df[df['Business_Type'] == bt]) > 0])}\")\n",
    "        \n",
    "        # Enhanced summary with insights\n",
    "        print(f\"\\n📊 Detailed Summary for {city}:\")\n",
    "        print(\"=\" * 80)\n",
    "        \n",
    "        total_with_phone = 0\n",
    "        total_with_website = 0\n",
    "        total_businesses = len(df)\n",
    "        \n",
    "        for business_type in self.business_types.keys():\n",
    "            business_df = df[df['Business_Type'] == business_type]\n",
    "            if not business_df.empty:\n",
    "                # Safe rating calculation\n",
    "                numeric_ratings = pd.to_numeric(business_df['Rating'], errors='coerce')\n",
    "                avg_rating = numeric_ratings.mean()\n",
    "                \n",
    "                # Count contact info availability\n",
    "                phone_count = len(business_df[business_df['Phone'].astype(str).str.strip() != ''])\n",
    "                website_count = len(business_df[business_df['Website'].astype(str).str.strip() != ''])\n",
    "                \n",
    "                total_with_phone += phone_count\n",
    "                total_with_website += website_count\n",
    "                \n",
    "                phone_pct = round((phone_count/len(business_df))*100, 1)\n",
    "                website_pct = round((website_count/len(business_df))*100, 1)\n",
    "                \n",
    "                print(f\"🏢 {business_type}:\")\n",
    "                print(f\"    📍 Total Locations: {len(business_df)}\")\n",
    "                print(f\"    📞 With Phone: {phone_count} ({phone_pct}%)\")\n",
    "                print(f\"    🌐 With Website: {website_count} ({website_pct}%)\")\n",
    "                print(f\"    ⭐ Avg Rating: {round(avg_rating, 2) if not pd.isna(avg_rating) else 'No Ratings'}\")\n",
    "                print(\"-\" * 60)\n",
    "        \n",
    "        # Overall statistics\n",
    "        print(f\"📈 OVERALL STATISTICS:\")\n",
    "        print(f\"    🏢 Total Businesses: {total_businesses}\")\n",
    "        if total_businesses > 0:\n",
    "            print(f\"    📞 Total with Phone: {total_with_phone} ({round((total_with_phone/total_businesses)*100, 1)}%)\")\n",
    "            print(f\"    🌐 Total with Website: {total_with_website} ({round((total_with_website/total_businesses)*100, 1)}%)\")\n",
    "        else:\n",
    "            print(\"    No businesses found to calculate overall statistics.\")\n",
    "        print(\"=\" * 80)\n",
    "        \n",
    "        print(f\"\\n💡 File Usage Tips:\")\n",
    "        print(\"    CSV Files:\")\n",
    "        print(\"      • Compatible with Excel, Google Sheets, and any spreadsheet software\")\n",
    "        print(\"      • Best for data analysis and importing into other tools\")\n",
    "        print(\"      • UTF-8 encoding supports international characters\")\n",
    "        print(\"    Excel File:\")\n",
    "        print(\"      • Single workbook with multiple organized sheets\")\n",
    "        print(\"      • 'All_Businesses' sheet contains complete combined data\")\n",
    "        print(\"      • Individual category sheets for focused analysis\")\n",
    "        print(\"      • 'Summary' sheet with statistics and insights\")\n",
    "        print(\"      • Better formatting and easier navigation\")\n",
    "    \n",
    "    def run_interactive(self):\n",
    "        \"\"\"\n",
    "        Enhanced interactive version with dual format output\n",
    "        \"\"\"\n",
    "        print(\"=\" * 70)\n",
    "        print(\"🏢 ENHANCED BUSINESS LOCATOR - CSV & EXCEL OUTPUT (Places API New)\")\n",
    "        print(\"=\" * 70)\n",
    "        print(\"📍 This tool will find the following business types:\")\n",
    "        \n",
    "        for idx, business_type in enumerate(self.business_types.keys(), 1):\n",
    "            print(f\"    {idx:2d}. {business_type}\")\n",
    "        \n",
    "        print(\"=\" * 70)\n",
    "        print(\"💡 Features:\")\n",
    "        print(\"    ✅ Phone numbers and websites included\")\n",
    "        print(\"    ✅ Output in both CSV and Excel formats\")\n",
    "        print(\"    ✅ Single Excel file with multiple organized sheets\")\n",
    "        print(\"    ✅ Combined data sheet + individual category sheets\")\n",
    "        print(\"    ✅ Summary statistics and percentages\")\n",
    "        print(\"    ✅ Individual CSV files for each business category\")\n",
    "        print(\"=\" * 70)\n",
    "        print(\"⚠️  Important Notes:\")\n",
    "        print(\"    • Output: CSV files + One comprehensive Excel file\")\n",
    "        print(\"    • Excel file contains multiple sheets (combined + individual categories)\")\n",
    "        print(\"    • Excel requires 'openpyxl' package: pip install openpyxl\")\n",
    "        print(\"    • Estimated time: 5-10 minutes for larger cities\")\n",
    "        print(\"    • Files saved with UTF-8 encoding\")\n",
    "        print(\"    • This version uses 'Places API (New)'. Ensure it's enabled in Google Cloud Console.\")\n",
    "        print(\"=\" * 70)\n",
    "        \n",
    "        while True:\n",
    "            try:\n",
    "                city = input(\"\\n🏙️  Enter city name (or 'quit' to exit): \").strip()\n",
    "                \n",
    "                if city.lower() in ['quit', 'exit', 'q']:\n",
    "                    print(\"👋 Thank you for using Enhanced Business Locator!\")\n",
    "                    break\n",
    "                \n",
    "                if not city:\n",
    "                    print(\"⚠️  Please enter a valid city name.\")\n",
    "                    continue\n",
    "                \n",
    "                # Confirmation for large searches\n",
    "                print(f\"\\n🚀 Starting enhanced search for {city}...\")\n",
    "                print(f\"⏱️  Estimated time: 5-10 minutes (fetching detailed data for {len(self.business_types)} categories)\")\n",
    "                print(\"💰 This will make multiple detailed API calls (ensure billing is enabled)\")\n",
    "                print(\"📄 Output: CSV files + One comprehensive Excel workbook\")\n",
    "                print(\"📑 Excel file will have combined data + individual category sheets\")\n",
    "                \n",
    "                confirm = input(\"Continue? (y/n): \").strip().lower()\n",
    "                if confirm not in ['y', 'yes']:\n",
    "                    continue\n",
    "                \n",
    "                # Record start time\n",
    "                start_time = time.time()\n",
    "                \n",
    "                # Get all business data\n",
    "                all_data = self.get_all_businesses(city)\n",
    "                \n",
    "                # Calculate execution time\n",
    "                end_time = time.time()\n",
    "                execution_time = round(end_time - start_time, 2)\n",
    "                \n",
    "                if all_data:\n",
    "                    print(f\"\\n⏱️  Search completed in {execution_time} seconds\")\n",
    "                    \n",
    "                    # Save the data in both formats\n",
    "                    self.save_to_files(all_data, city)\n",
    "                    \n",
    "                    # Ask if user wants to continue\n",
    "                    print(\"\\n\" + \"=\"*60)\n",
    "                    continue_choice = input(\"🔄 Search another city? (y/n): \").strip().lower()\n",
    "                    if continue_choice not in ['y', 'yes']:\n",
    "                        print(\"👋 Thank you for using Enhanced Business Locator!\")\n",
    "                        break\n",
    "                else:\n",
    "                    print(f\"❌ No businesses found for {city}. Please try another city or refine search terms.\")\n",
    "                    \n",
    "            except KeyboardInterrupt:\n",
    "                print(\"\\n\\n👋 Program interrupted. Goodbye!\")\n",
    "                break\n",
    "            except Exception as e:\n",
    "                print(f\"❌ An unexpected error occurred: {e}\")\n",
    "                print(\"Please try again or contact support if the issue persists.\")\n",
    "                continue\n",
    "\n",
    "def main():\n",
    "    \"\"\"\n",
    "    Enhanced main function with dual format setup instructions, guiding the user\n",
    "    through Google Cloud Console prerequisites if the API key fails validation.\n",
    "    \"\"\"\n",
    "    print(\"🔑 Enhanced Google Maps API Business Locator - CSV & Excel Output\")\n",
    "    print(\"=\" * 70)\n",
    "    \n",
    "    # Check for required packages\n",
    "    try:\n",
    "        import openpyxl\n",
    "        excel_available = True\n",
    "        print(\"✅ Excel support: Available (openpyxl found)\")\n",
    "    except ImportError:\n",
    "        excel_available = False\n",
    "        print(\"⚠️  Excel support: Limited (install openpyxl for full Excel support)\")\n",
    "        print(\"    Run: pip install openpyxl\")\n",
    "    \n",
    "    print(\"\\n--- API Key Setup Guide ---\")\n",
    "    print(\"To use this tool, you need a Google Maps API Key with specific APIs enabled.\")\n",
    "    print(\"If you encounter 'REQUEST_DENIED' errors, please follow these steps carefully:\")\n",
    "    print(\"===================================================================\")\n",
    "    print(\"1. 🌐  Go to Google Cloud Console: https://console.cloud.google.com\")\n",
    "    print(\"2. 📁  Select or Create a Project. (Top left dropdown menu)\")\n",
    "    print(\"3. 💳  Enable Billing for your project. (Required for all Places API usage)\")\n",
    "    print(\"4. 🔧  Enable Necessary APIs:\")\n",
    "    print(\"      Navigate to 'APIs & Services' > 'Enabled APIs & Services'.\")\n",
    "    print(\"      Click '+ ENABLE APIS AND SERVICES' and search for & enable:\")\n",
    "    print(\"      •  'Places API' (This is crucial for the script to work)\")\n",
    "    print(\"5. 🔑  Create or Get Your API Key:\")\n",
    "    print(\"      Go to 'APIs & Services' > 'Credentials'.\")\n",
    "    print(\"      Create a new API key or copy an existing one.\")\n",
    "    print(\"6. 🔒  Restrict Your API Key (Highly Recommended for security):\")\n",
    "    print(\"      Edit your API key and under 'API restrictions', select 'Restrict key' to 'Places API'.\")\n",
    "    print(\"===================================================================\")\n",
    "    print(\"Once these steps are done, enter your API key below.\")\n",
    "\n",
    "    api_key = input(\"\\nEnter your Google Maps API key: \").strip()\n",
    "    \n",
    "    if not api_key:\n",
    "        print(\"\\n❌ API key is required to use this tool. Please restart and provide it.\")\n",
    "        return\n",
    "    \n",
    "    try:\n",
    "        print(\"\\n🔄 Initializing and validating API key...\")\n",
    "        \n",
    "        # Initialize the locator\n",
    "        locator = BusinessLocator(api_key)\n",
    "        \n",
    "        # Test the API key with a simple query using the new find_place method\n",
    "        # This will use the \"Find Place From Text\" (New) endpoint\n",
    "        test_result = locator.gmaps.find_place(\n",
    "            input=\"test restaurant in New York\",\n",
    "            input_type='textquery',\n",
    "            fields=['place_id'] # Request minimal fields for a quick test\n",
    "        )\n",
    "        if 'candidates' in test_result and test_result['candidates']:\n",
    "            print(\"✅ API key validated successfully using Places API (New)!\")\n",
    "        else:\n",
    "            # If no candidates found, it might still be valid but with no matching results\n",
    "            # or some other issue. Guide the user back to the setup.\n",
    "            print(\"⚠️  API key validation inconclusive. This could mean:\")\n",
    "            print(\"    - No test results found (which is rare but possible).\")\n",
    "            print(\"    - The API key is not fully configured or has incorrect permissions.\")\n",
    "            print(\"    Please double-check the API Key Setup Guide above.\")\n",
    "            return # Exit if validation is inconclusive to prevent further errors\n",
    "        \n",
    "        # Show dual output benefits\n",
    "        print(\"\\n📄 Dual Format Output Benefits:\")\n",
    "        print(\"    CSV Files:\")\n",
    "        print(\"      ✅ Universal compatibility (Excel, Google Sheets, etc.)\")\n",
    "        print(\"      ✅ Easy data import for analysis tools\")\n",
    "        print(\"      ✅ Lightweight and fast to open\")\n",
    "        print(\"    Excel File:\")\n",
    "        print(\"      ✅ Single comprehensive workbook with multiple sheets\")\n",
    "        print(\"      ✅ 'All_Businesses' sheet with complete combined data\")\n",
    "        print(\"      ✅ Individual category sheets for focused analysis\")\n",
    "        print(\"      ✅ 'Summary' sheet with statistics and insights\")\n",
    "        print(\"      ✅ Better formatting and presentation\")\n",
    "        \n",
    "        proceed = input(f\"\\nProceed with dual-format output? (y/n): \").strip().lower()\n",
    "        if proceed not in ['y', 'yes']:\n",
    "            print(\"👋 Exiting. Thank you!\")\n",
    "            return\n",
    "        \n",
    "        # Run the interactive locator\n",
    "        locator.run_interactive()\n",
    "        \n",
    "    except googlemaps.exceptions.ApiError as e:\n",
    "        print(f\"\\n❌ API Error: {e}\")\n",
    "        print(\"📋 This error often means your API key isn't fully set up.\")\n",
    "        print(\"   Please review the 'API Key Setup Guide' provided above.\")\n",
    "        print(f\"   Specific error details: {e}\")\n",
    "    except Exception as e:\n",
    "        print(f\"\\n❌ An unexpected error occurred during API key initialization or validation: {e}\")\n",
    "        print(\"   Please ensure you have an active internet connection and your API key is correctly entered.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Display package requirements\n",
    "    print(\"📦 Required packages:\")\n",
    "    print(\"    Essential: googlemaps, pandas\")\n",
    "    print(\"    For Excel: openpyxl\")\n",
    "    print(\"💻 Install/Upgrade with: pip install --upgrade googlemaps pandas openpyxl\") # Added upgrade for googlemaps\n",
    "    print(\"=\" * 70)\n",
    "    \n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
